homepage: "https://github.com/google/guice"
language: jvm
primary_contact: ""
auto_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/google/guice.git"